# Generated by Django 4.1.7 on 2023-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
