# Generated by Django 4.1.7 on 2023-06-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
