# Generated by Django 4.1.7 on 2023-06-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_subcategory_remove_category_photo_reklama_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetest',
            name='onlinereklama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.reklama'),
        ),
        migrations.AlterField(
            model_name='blogtable',
            name='blogtable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.reklama'),
        ),
    ]
