# Generated by Django 4.1.7 on 2023-06-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_subcategory_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='blogtable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.aksiya'),
        ),
    ]
